//
//  XYUIDesign.h
//  XYUIDesign
//
//  Created by Xu Xiaoye on 4/3/13.
//  Copyright (c) 2013 XY. All rights reserved.
//
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

// ThirdParty
#import "SBJson.h"

//#import <MDF/MDF.h"

// Utility
// --> // #import "XYListData.h"
// --> // #import "XYStack.h"
#import "XYLabelValue.h"
#import "XYConnector.h"
#import "XYConnectorManager.h"
// --> // #import "XYCascadeSelection.h"
#import "XYBaseAppDelegate.h"
#import "XYUtility.h"
#import "XYSelectOption.h"
#import "XYFieldSelectOption.h"
#import "XYBaseErrorCenter.h"
#import "XYErrorInfo.h"
// --> // #import "XYCursor.h"
#import "XYKeyboardListener.h"
#import "XYSkinManager.h"
// --> // #import "XYLoginContext.h"
// --> // #import "RXMLElement.h"
// --> // #import "XYDefaultPieChartDelegator.h"

// Fields
#import "XYField.h"
// --> // #import "XYLoadMoreButtonField.h"
#import "XYDatePickerField.h"
#import "XYInputTextField.h"
#import "XYInputTextViewField.h"
#import "XYPickerField.h"
#import "XYSelectionField.h"
#import "XYSelectionFieldDataSource.h"
#import "XYSelectionItemField.h"
#import "XYUIDatePickerTextFieldDelegate.h"
#import "XYUISelectionTextViewDelegate.h"
#import "XYUITextFieldDelegate.h"
#import "XYUITextViewDelegate.h"
#import "XYAdvField.h"
#import "XYAdvFieldDelegate.h"
#import "XYDynaSearchField.h"
#import "XYSelectOptionField.h"
#import "XYDynaSearchSelectionField.h"
#import "XYAdvSearchField.h"
#import "XYAdvSearchFieldDelegate.h"

// Views
#import "XYAnimation.h"
#import "XYBaseView.h"
#import "XYViewDelegate.h"
#import "XYFieldView.h"
#import "XYActivityIndicatorView.h"
#import "XYInputTextFieldView.h"
#import "XYInputTextViewView.h"
#import "XYSideView.h"
// --> // #import "MKNumberBadgeView.h"
// --> // #import "XYFavCustomerView.h"
#import "XYUIAlertView.h"
#import "XYAnimationView.h"
#import "XYAnimationViewDelegate.h"
#import "XYNotificationView.h"
#import "XYProcessbarView.h"
// --> // #import "XYCardContainerView.h"
// --> // #import "XYCardView.h"
// --> // #import "XYActionSheetViewDelegate.h"
// --> // #import "XYActionSheetView.h"
// --> // #import "XYMenuView.h"
// --> // #import "XYCardContainerView.h"
// --> // #import "XYCardView.h"
// --> // #import "XYCardContainerViewDataSource.h"
// --> // #import "XYCardContainerViewDelegate.h"
// --> // #import "XYCardViewDelegate.h"
#import "XYBubbleView.h"
// --> // #import "XYUITextView.h"
// --> // #import "XYMultipleInputTextView.h"
// --> // #import "XYMultipleInputTextViewDelegate.h"
#import "XYUIAlertView2.h"
#import "XYActivityIndicatorIconView.h"
#import "XYProgressIndicatorView.h"
// --> // #import "XYTableCellBadgeView.h"
#import "XYUISegmentedControl.h"
#import "XYImageListView.h"
#import "XYPagedView.h"
#import "XYActivityIndicatorBarView.h"

// Table
#import "XYTableCell.h"
#import "XYDummyTableCell.h"
#import "XYTableCellFactory.h"
#import "XYTableContainer.h"
#import "XYTableSection.h"
#import "XYDynamicTableCell.h"
#import "XYExpandableTableCell.h"
#import "XYButtonTableCell.h"
#import "XYRollableTableCell.h"
#import "XYSelectionItemTableCell.h"
#import "XYSelectionTableCell.h"
#import "XYBubbleTableCell.h"
// --> // #import "XYLineTableCell.h"
#import "XYValueHelpTableCell.h"

// View controllers
#import "XYBaseUIViewController.h"
// --> // #import "XYBaseDetailViewController.h"
// --> // #import "XYBaseListViewController.h"
// --> // #import "XYBaseSearchViewController.h"
// --> // #import "XYBaseSearchViewController2.h"
#import "XYBaseUITableViewController.h"
// --> // #import "XYBaseSplitDetailViewController.h"
#import "XYBaseSplitViewController.h"
// --> // #import "XYCustomerDetailViewController.h"
// --> // #import "XYCustomerSearchResultViewController.h"
// --> // #import "XYCustomerSearchViewController.h"
#import "XYBasePopOverViewController.h"
// --> // #import "XYGeneralInitialViewController.h"
// --> // #import "XYGeneralInitialTableViewController.h"
// --> // #import "XYBaseBubbleViewController.h"
#import "XYSelectionListViewController.h"
#import "XYSelectOptionViewController.h"
#import "XYDynaSearchFieldViewController.h"
#import "XYSelectOptionViewController.h"
#import "XYErrorReportViewController.h"
// --> // #import "XYCreateITDirectTicketViewController.h"
#import "XYDynaSearchSelectionFieldViewController.h"
#import "XYAdvSearchFieldViewController.h"
#import "XYWelcomeViewController.h"
#import "XYVersionViewController.h"

// Misc1
// --> // #import "XYBaseDataCenter.h"
// --> // #import "XYBaseControlCenter.h"
#import "XYBaseUITableViewDelegate.h"
#import "XYBaseUITableViewMethods.h"
#import "XYBusyProcessDelegate2.h"
#import "XYBusyProcessorDelegate.h"
#import "XYLoadMore.h"
#import "XYProcessResult.h"
#import "XYSelectorObject.h"
#import "XYUIDesign.h"
#import "XYUIStatusUpdater.h"
#import "XYStatusUpdateDelegate.h"
#import "UIDesighHeader.h"
// --> // #import "XYFavoriteCustomerItem.h"
#import "XYDynaSearchFieldDelegate.h"
#import "XYAdvFieldViewControllerDelegate.h"

// Messaging part
#import "XYMessageAgent.h"
#import "XYMessageEngine.h"
// --> // #import "XYBaseMessageEngine.h"
// --> // #import "XYGlobalMessageInterceptor.h"
// --> // #import "XYMDFMessageEngine.h"
// --> // #import "XYMessageEngine.h"
// --> // #import "XYMessageFactory.h"
// --> // #import "XYMessageInterceptor.h"
// --> // #import "XYMessageNDN.h"
// --> // #import "XYMessageNDNHandler.h"
// --> // #import "XYNDNDeNormalizeException.h"
// --> // #import "XYNDNNormalizeException.h"
// --> // #import "XYNetworkFailureException.h"
// --> // #import "XYNetworkTimeoutException.h"
// --> // #import "XYNoClassFoundException.h"
// --> // #import "XYNoNDNHandlerException.h"
// --> // #import "XYResponseErrorException.h"
// --> // #import "XYSOAPFaultException.h"
// --> // #import "XYRequest.h"
// --> // #import "XYResponse.h"
// --> // #import "XYAppRequest.h"
// --> // #import "XYAppResponse.h"
// --> // #import "XYTextResponse.h"
// --> // #import "XYXMLResponse.h"
// --> // #import "XYODataRequest.h"
// --> // #import "XYODataResponse.h"
// --> // #import "XYMDFMessageNDNHandler.h"

// Search engine part
// --> // #import "XYBaseEntity.h"
// --> // #import "XYBaseDetailEntity.h"
// --> // #import "XYBaseResultEntity.h"
// --> // #import "XYBaseSearchEntity.h"
// --> // #import "XYBaseSearchEngine.h"
// --> // #import "XYSearchEngine.h"
// --> // #import "XYSearchEngineFactory.h"
// --> // #import "XYGatewaySearchEngine.h"

// --> // #import "XYBPAccountSearchEntity.h"
// --> // #import "XYBPAccountResultEntity.h"
// --> // #import "XYBPAccountDetailEntity.h"
// --> // #import "XYBPAccountSearchEngine.h"

// Download
// --> // #import "XYDownloader.h"
// --> // #import "XYDownloaderDelegate.h"
// --> // #import "XYBaseDownloader.h"
// --> // #import "XYSearchEngineDownloader.h"

// BW report handling
// --> // #import "XYBIQueryAxisInfo.h"
// --> // #import "XYBIQueryAxisData.h"
// --> // #import "XYBIQueryCellData.h"
// --> // #import "XYBIQueryTextSymbols.h"
// --> // #import "XYBIQueryHandler.h"
// --> // #import "XYBIQueryResult.h"

// CoreData
// --> // #import "XYProperty.h"
// --> // #import "XYCoreDataConnector.h"
// --> // #import "XYCoreDataManager.h"

// ThirdParty
// --> // #import "SSCheckBoxView.h"

@interface XYUIDesign : NSObject

-(NSString*)version;
-(NSString*)versionUpdateDetail;
@end
